/*
 * Copyright (C) 2025-2026 Garrett Brown
 * This file is part of meditation.surf - https://github.com/SwellPatrol/meditation.surf
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * See the file LICENSE.txt for more information.
 */

export { DemoExperienceFactory } from "./bootstrap/DemoExperienceFactory";
export { MeditationExperience } from "./experience/MeditationExperience";
export {
  AudioPolicy,
  CapabilityOracle,
  CommittedPlaybackChooser,
  FocusDelayController,
  MediaExecutionController,
  MediaInventoryCloner,
  MediaKernelController,
  MediaKernelExperienceBridge,
  MediaThumbnailController,
  MediaThumbnailFrameSelector,
  MediaSessionPlanner,
  VariantPolicy,
  type AudioActivationMode,
  type AudioActivationIntent,
  type AudioCapabilityProfile,
  type AudioExecutionSnapshot,
  type AudioFallbackMode,
  type AudioMode,
  type AudioPolicyDecision,
  type AudioPolicyDecisionReason,
  type AudioPolicyInput,
  type AudioTrackPolicy,
  type AppMediaCapabilities,
  type CapabilityDecision,
  type CapabilityDecisionReason,
  type CapabilityProbeResult,
  type CommittedPlaybackChooserInput,
  type CommittedPlaybackDecision,
  type CommittedPlaybackDecisionReason,
  type CommittedPlaybackIntent,
  type CommittedPlaybackLanePreference,
  type CommittedPlaybackLifecycleState,
  type CommittedPlaybackMode,
  type CommittedPlaybackSnapshot,
  type CustomDecodeCapability,
  type CustomDecodeDecision,
  type CustomDecodeDecisionReason,
  type CustomDecodeFrameHandle,
  type CustomDecodeLane,
  type CustomDecodeSessionAdapter,
  type CustomDecodeSessionState,
  type CustomDecodeSnapshot,
  type FocusDelayState,
  type FocusDelayStateListener,
  type MediaExecutionCommand,
  type MediaExecutionCommandType,
  type MediaExecutionResult,
  type MediaExecutionSnapshot,
  type MediaExecutionState,
  type MediaExecutionStateListener,
  type MediaBrowseContentResolver,
  type MediaBrowseFocusController,
  type MediaBrowseFocusState,
  type MediaBrowseSelectionController,
  type MediaBrowseSelectionState,
  type MediaCapabilityProfile,
  type MediaIntent,
  type MediaIntentType,
  type MediaInventory,
  type MediaInventoryProvider,
  type MediaInventoryRequest,
  type MediaInventoryResult,
  type MediaInventorySelectionReason,
  type MediaInventorySnapshot,
  type MediaInventorySource,
  type MediaInventorySupportLevel,
  type MediaAudioTrackInfo,
  type MediaTextTrackInfo,
  type MediaVariantInfo,
  type MediaKernelItem,
  type MediaKernelState,
  type MediaKernelStateListener,
  type MediaPlan,
  type MediaPlanReason,
  type MediaPlanSession,
  type MediaPlaybackLane,
  type MediaPlaybackSequenceController,
  type MediaPlaybackSequenceState,
  type MediaRoleCapabilityRequest,
  type MediaRoleCapabilitySnapshot,
  type MediaRendererKind,
  type MediaRuntimeAdapter,
  type MediaRuntimeCapabilities,
  type MediaRuntimeSupportLevel,
  type MediaRuntimeSessionHandle,
  type MediaStartupDebugState,
  type MediaSessionDescriptor,
  type MediaSessionPlannerInput,
  type MediaSessionPriority,
  type MediaSessionRole,
  type MediaSessionSnapshot,
  type MediaSessionState,
  type MediaSessionVisibility,
  type MediaSourceDescriptor,
  type MediaSourceKind,
  type MediaSourcePlaybackSource,
  type MediaThumbnailCacheEntry,
  type MediaThumbnailCandidateFrame,
  type MediaThumbnailDescriptor,
  type MediaThumbnailExtractionAttempt,
  type MediaThumbnailExtractionResult,
  type MediaThumbnailExtractionPolicy,
  type MediaThumbnailExtractionStrategy,
  type MediaThumbnailFallbackBehavior,
  type MediaThumbnailFrameRejectionReason,
  type MediaThumbnailPriority,
  type MediaThumbnailQuality,
  type MediaThumbnailQualityIntent,
  type MediaThumbnailRequest,
  type MediaThumbnailResult,
  type MediaThumbnailRuntimeAdapter,
  type MediaThumbnailRuntimeCapabilities,
  type MediaThumbnailSelectionDecision,
  type MediaThumbnailSelectionReason,
  type MediaThumbnailSnapshot,
  type MediaThumbnailSnapshotListener,
  type MediaThumbnailState,
  type PreviewCandidate,
  type PreviewCandidateInput,
  type PreviewCandidateScore,
  type PreviewEvictionReason,
  type PreviewFarmAssignment,
  type PreviewFarmBudget,
  type PreviewFarmCandidate,
  type PreviewFarmCandidateRank,
  PreviewFarmController,
  type PreviewFarmEvictionReason,
  type PreviewFarmSessionState,
  type PreviewFarmSnapshot,
  type PreviewFarmState,
  type PreviewFarmTransitionReason,
  type PreviewSchedulerBudget,
  type PreviewSchedulerDecision,
  type PreviewSchedulerDecisionReason,
  type PreviewSessionAssignment,
  type PreviewWarmState,
  MediaTelemetryController,
  AdaptiveBudgetPolicy,
  type AdaptiveBudgetDecision,
  type AdaptiveBudgetDecisionReason,
  RendererRouter,
  type CustomDecodeTelemetryEvent,
  type MediaTelemetryEvent,
  type RendererBackendKind,
  type RendererCapability,
  type RendererDecision,
  type RendererDecisionReason,
  type RendererFrameHandle,
  type RendererSessionBinding,
  type RendererSnapshot,
  type RendererTelemetryEvent,
  type RuntimeGuardrailReason,
  type RuntimeGuardrailState,
  type StartupTelemetryEvent,
  type TelemetryCounters,
  type TelemetryRollingWindow,
  type TelemetrySnapshot,
  type ThumbnailTelemetryEvent,
  type VariantQualityTier,
  type VariantRolePolicy,
  type VariantSelectionDecision,
  type VariantSelectionReason,
  type VariantSelectionRequest,
  type MediaWarmth,
} from "@meditation-surf/media";
export type {
  AppLayout,
  BackgroundLayerLayout,
  CenteredOverlayLayout,
  CenteredOverlayPlacement,
  CenteredOverlaySize,
  ForegroundLayerLayout,
} from "@meditation-surf/layout";
export { MediaSourceDescriptorFactory } from "./catalog/MediaSourceDescriptorFactory";
export {
  BackgroundVideoModel,
  type BackgroundVideoPlaybackPolicy,
} from "./playback/BackgroundVideoModel";
export {
  PlaybackSequenceController,
  type PlaybackSequenceListener,
  type PlaybackSequenceState,
} from "./playback/PlaybackSequenceController";
export { ForegroundUiElement } from "./ui/ForegroundUiElement";
export type {
  ForegroundUiElementPlacement,
  ForegroundUiElementSize,
} from "./ui/ForegroundUiElement";
export { ForegroundUiModel } from "./ui/ForegroundUiModel";
export type { ICatalogClient } from "./api/ICatalogClient";
export {
  AppLaunchedAnalyticsEvent,
  type AppLaunchedAnalyticsEventApp,
  type AppLaunchedAnalyticsEventPayload,
} from "./analytics/AppLaunchedAnalyticsEvent";
export {
  AudioPreferencesChangedAnalyticsEvent,
  type AudioPreferencesChangedAnalyticsEventPayload,
} from "./analytics/AudioPreferencesChangedAnalyticsEvent";
export {
  CatalogLoadedAnalyticsEvent,
  type CatalogLoadedAnalyticsEventPayload,
} from "./analytics/CatalogLoadedAnalyticsEvent";
export type { IAnalyticsEvent } from "./analytics/IAnalyticsEvent";
export {
  PlaybackStartedAnalyticsEvent,
  type PlaybackStartedAnalyticsEventPayload,
} from "./analytics/PlaybackStartedAnalyticsEvent";
export { Catalog } from "./catalog/Catalog";
export { CatalogSection } from "./catalog/CatalogSection";
export { FixtureCatalog } from "./catalog/FixtureCatalog";
export { MediaItem } from "./catalog/MediaItem";
export {
  MediaItemMetadata,
  type MediaItemMetadataInit,
  type MediaItemMetadataRow,
  type MediaItemMetadataTag,
} from "./catalog/MediaItemMetadata";
export {
  AudioPreferences,
  type AudioPreferencesInit,
} from "./preferences/AudioPreferences";
export type { IAudioPreferencesStorage } from "./preferences/IAudioPreferencesStorage";
export { BrowserAudioPreferencesStorage } from "./preferences/BrowserAudioPreferencesStorage";
